<?php

namespace PackageVersions;

/**
 * This class is generated by ocramius/package-versions, specifically by
 * @see \PackageVersions\Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 */
final class Versions
{
    const ROOT_PACKAGE_NAME = 'symfony/website-skeleton';
    const VERSIONS = array (
  'doctrine/annotations' => 'v1.6.0@c7f2050c68a9ab0bdb0f98567ec08d80ea7d24d5',
  'doctrine/cache' => 'v1.8.0@d768d58baee9a4862ca783840eca1b9add7a7f57',
  'doctrine/collections' => 'v1.5.0@a01ee38fcd999f34d9bfbcee59dbda5105449cbf',
  'doctrine/common' => 'v2.10.0@30e33f60f64deec87df728c02b107f82cdafad9d',
  'doctrine/dbal' => 'v2.8.0@5140a64c08b4b607b9bedaae0cedd26f04a0e621',
  'doctrine/doctrine-bundle' => '1.10.0@82d2c63cd09acbde2332f55d9aa7b28aefe4983d',
  'doctrine/doctrine-cache-bundle' => '1.3.5@5514c90d9fb595e1095e6d66ebb98ce9ef049927',
  'doctrine/doctrine-migrations-bundle' => 'v1.3.1@a9e506369f931351a2a6dd2aef588a822802b1b7',
  'doctrine/event-manager' => 'v1.0.0@a520bc093a0170feeb6b14e9d83f3a14452e64b3',
  'doctrine/inflector' => 'v1.3.0@5527a48b7313d15261292c149e55e26eae771b0a',
  'doctrine/instantiator' => '1.1.0@185b8868aa9bf7159f5f953ed5afb2d7fcdc3bda',
  'doctrine/lexer' => 'v1.0.1@83893c552fd2045dd78aef794c31e694c37c0b8c',
  'doctrine/migrations' => 'v1.8.1@215438c0eef3e5f9b7da7d09c6b90756071b43e6',
  'doctrine/orm' => 'v2.6.3@434820973cadf2da2d66e7184be370084cc32ca8',
  'doctrine/persistence' => 'v1.1.0@c0f1c17602afc18b4cbd8e1c8125f264c9cf7d38',
  'doctrine/reflection' => 'v1.0.0@02538d3f95e88eb397a5f86274deb2c6175c2ab6',
  'egulias/email-validator' => '2.1.6@0578b32b30b22de3e8664f797cf846fc9246f786',
  'fig/link-util' => '1.0.0@1a07821801a148be4add11ab0603e4af55a72fac',
  'jdorn/sql-formatter' => 'v1.2.17@64990d96e0959dff8e059dfcdc1af130728d92bc',
  'monolog/monolog' => '1.24.0@bfc9ebb28f97e7a24c45bdc3f0ff482e47bb0266',
  'ocramius/package-versions' => '1.3.0@4489d5002c49d55576fa0ba786f42dbb009be46f',
  'ocramius/proxy-manager' => '2.1.1@e18ac876b2e4819c76349de8f78ccc8ef1554cd7',
  'phpdocumentor/reflection-common' => '1.0.1@21bdeb5f65d7ebf9f43b1b25d404f87deab5bfb6',
  'phpdocumentor/reflection-docblock' => '4.3.0@94fd0001232e47129dd3504189fa1c7225010d08',
  'phpdocumentor/type-resolver' => '0.4.0@9c977708995954784726e25d0cd1dddf4e65b0f7',
  'psr/cache' => '1.0.1@d11b50ad223250cf17b86e38383413f5a6764bf8',
  'psr/container' => '1.0.0@b7ce3b176482dbbc1245ebf52b181af44c2cf55f',
  'psr/link' => '1.0.0@eea8e8662d5cd3ae4517c9b864493f59fca95562',
  'psr/log' => '1.1.0@6c001f1daafa3a3ac1d8ff69ee4db8e799a654dd',
  'psr/simple-cache' => '1.0.1@408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
  'sensio/framework-extra-bundle' => 'v5.2.2@9ef408febe2f12e70118ef61c6515035a06c5830',
  'swiftmailer/swiftmailer' => 'v6.1.3@8ddcb66ac10c392d3beb54829eef8ac1438595f4',
  'symfony/asset' => 'v4.2.0@fb06338fd3762f8615b51a58e5e9299ccca03876',
  'symfony/cache' => 'v4.2.0@dbe98af4943a9c246e4538868e0fa55bc8b5e0f3',
  'symfony/config' => 'v4.2.0@10ba96d42cc9a482bce05c8179f06e24e665c920',
  'symfony/console' => 'v4.2.0@4dff24e5d01e713818805c1862d2e3f901ee7dd0',
  'symfony/contracts' => 'v1.0.0@4a33574d5771f4b04334cd4f7d43de96a92efb62',
  'symfony/debug' => 'v4.2.0@e0a2b92ee0b5b934f973d90c2f58e18af109d276',
  'symfony/dependency-injection' => 'v4.2.0@c2061bce5915f853a619f02ce1278ca83156d375',
  'symfony/doctrine-bridge' => 'v4.2.0@9f66793ce023d1c2b50ba6f3141dacf54ad2f651',
  'symfony/dotenv' => 'v4.2.0@97f135ab40f969cbeae27d482ff63acbc33dbe2a',
  'symfony/event-dispatcher' => 'v4.2.0@9b788b5f7cd6be22918f3d18ee3ff0a78e060137',
  'symfony/expression-language' => 'v4.2.0@2d2741ecba77e1cb27b726f12a6d43cfc2f199af',
  'symfony/filesystem' => 'v4.2.0@2f4c8b999b3b7cadb2a69390b01af70886753710',
  'symfony/finder' => 'v4.2.0@e53d477d7b5c4982d0e1bfd2298dbee63d01441d',
  'symfony/flex' => 'v1.1.8@955774ecf07b10230bb5b44e150ba078b45f68fa',
  'symfony/form' => 'v4.2.0@e098c91c7daec1e9da3ffd95164d778ab32f9796',
  'symfony/framework-bundle' => 'v4.2.0@6953f43de8244c601884b1a0ecbae1a2be32838f',
  'symfony/http-foundation' => 'v4.2.0@1b31f3017fadd8cb05cf2c8aebdbf3b12a943851',
  'symfony/http-kernel' => 'v4.2.0@500409e5d8a31fc92450a0ec2ea4e4c35af40117',
  'symfony/inflector' => 'v4.2.0@f9a637c0359f74404d44cf0da0a3ce53bae0787e',
  'symfony/intl' => 'v4.2.0@1730183319d8b1f74143a3ed16473b229dc94cec',
  'symfony/monolog-bridge' => 'v4.2.0@95538500b45bb96d4bf90c7fdfe615318a777dea',
  'symfony/monolog-bundle' => 'v3.3.1@572e143afc03419a75ab002c80a2fd99299195ff',
  'symfony/options-resolver' => 'v4.2.0@a9c38e8a3da2c03b3e71fdffa6efb0bda51390ba',
  'symfony/orm-pack' => 'v1.0.5@1b58f752cd917a08c9c8df020781d9c46a2275b1',
  'symfony/polyfill-intl-icu' => 'v1.10.0@f22a90256d577c7ef7efad8df1f0201663d57644',
  'symfony/polyfill-mbstring' => 'v1.10.0@c79c051f5b3a46be09205c73b80b346e4153e494',
  'symfony/process' => 'v4.2.0@2b341009ccec76837a7f46f59641b431e4d4c2b0',
  'symfony/property-access' => 'v4.2.0@b6df4e1849f389468edb36e2e59877d4a8170723',
  'symfony/property-info' => 'v4.2.0@d34c76cfe2d16c594e26d0d11fabfef77b3651e5',
  'symfony/routing' => 'v4.2.0@97b9f457df748357eec101df5c8b1c649b543241',
  'symfony/security-bundle' => 'v4.2.0@705b5852306fb2bbf3b7903e7929eed01fc2c9d9',
  'symfony/security-core' => 'v4.2.0@faad8794fb93779a32d41cd312265480a417b375',
  'symfony/security-csrf' => 'v4.2.0@0aed738ad254d8bad49f845cfaf3984079934967',
  'symfony/security-guard' => 'v4.2.0@62335fd15d9f1289b1ebaff0ae72ebd9fcac3dd2',
  'symfony/security-http' => 'v4.2.0@34e089af7d363bd2ded8ad15f06b2b97348b97e5',
  'symfony/serializer' => 'v4.2.0@830a3add86777766b4fc6490e3f5e72d693704c2',
  'symfony/serializer-pack' => 'v1.0.1@35cea385ea44d1f40ec12571996bf768fbe409de',
  'symfony/swiftmailer-bundle' => 'v3.2.4@bd47db86d0b8415f6317c2be149bbacfab11a9cf',
  'symfony/translation' => 'v4.2.0@ff9a878c9b8f8bcd4d9138e2d32f508c942773d9',
  'symfony/twig-bridge' => 'v4.2.0@c0aea0ffe3417d5b4fbdb2346f79e5d1abe63ab9',
  'symfony/twig-bundle' => 'v4.2.0@2842f70b899ab765b3eaccdd3b8cdbb0cbb69fb6',
  'symfony/validator' => 'v4.2.0@ad13cdf1242f2ab1eb8a26eb8c9edb7733c84694',
  'symfony/var-exporter' => 'v4.2.0@08250457428e06289d21ed52397b0ae336abf54b',
  'symfony/web-link' => 'v4.2.0@f01264f10e4600c25057e257f3aafcfae586497a',
  'symfony/yaml' => 'v4.2.0@c41175c801e3edfda90f32e292619d10c27103d7',
  'twig/twig' => 'v2.5.0@6a5f676b77a90823c2d4eaf76137b771adf31323',
  'webmozart/assert' => '1.3.0@0df1908962e7a3071564e857d86874dad1ef204a',
  'zendframework/zend-code' => '3.3.1@c21db169075c6ec4b342149f446e7b7b724f95eb',
  'zendframework/zend-eventmanager' => '3.2.1@a5e2583a211f73604691586b8406ff7296a946dd',
  'easycorp/easy-log-handler' => 'v1.0.7@5f95717248d20684f88cfb878d8bf3d78aadcbba',
  'facebook/webdriver' => '1.6.0@bd8c740097eb9f2fc3735250fc1912bc811a954e',
  'nikic/php-parser' => 'v4.1.0@d0230c5c77a7e3cfa69446febf340978540958c0',
  'symfony/browser-kit' => 'v4.2.0@db7e59fec9c82d45e745eb500e6ede2d96f4a6e9',
  'symfony/css-selector' => 'v4.2.0@aa9fa526ba1b2ec087ffdfb32753803d999fcfcd',
  'symfony/debug-bundle' => 'v4.2.0@e52fc6ac1fe1150316f9991342ac2b4a9c1e1995',
  'symfony/debug-pack' => 'v1.0.6@630548c117a5f9e27d3385787641629945b6de50',
  'symfony/dom-crawler' => 'v4.2.0@7438a32108fdd555295f443605d6de2cce473159',
  'symfony/maker-bundle' => 'v1.9.0@e873047b6022a0343c9354f65d5d47b9e351dd53',
  'symfony/panther' => 'v0.2.0@d67f9dbcac173150fe00673e6564b3482762c615',
  'symfony/phpunit-bridge' => 'v4.2.0@3f03b625710f24071e2937e88112e9a19099c9eb',
  'symfony/polyfill-php72' => 'v1.10.0@9050816e2ca34a8e916c3a0ae8b9c2fccf68b631',
  'symfony/profiler-pack' => 'v1.0.3@fa2e2dad522a3bef322196abad28ffce6d0fdbc5',
  'symfony/stopwatch' => 'v4.2.0@ec076716412274e51f8a7ea675d9515e5c311123',
  'symfony/test-pack' => 'v1.0.4@94d1c2b02f137201cd6a68d290caa38fe3817cba',
  'symfony/var-dumper' => 'v4.2.0@db61258540350725f4beb6b84006e32398acd120',
  'symfony/web-profiler-bundle' => 'v4.2.0@dcbd06c328d843b4af328818b1ed1baeb08a85a3',
  'symfony/web-server-bundle' => 'v4.2.0@6291444989fc753df2a9c86e5f6d5af4616804f5',
  'paragonie/random_compat' => '2.*@',
  'symfony/polyfill-ctype' => '*@',
  'symfony/polyfill-iconv' => '*@',
  'symfony/polyfill-php71' => '*@',
  'symfony/polyfill-php70' => '*@',
  'symfony/polyfill-php56' => '*@',
  'symfony/website-skeleton' => 'v4.2.0.2@',
);

    private function __construct()
    {
    }

    /**
     * @throws \OutOfBoundsException if a version cannot be located
     */
    public static function getVersion(string $packageName) : string
    {
        if (isset(self::VERSIONS[$packageName])) {
            return self::VERSIONS[$packageName];
        }

        throw new \OutOfBoundsException(
            'Required package "' . $packageName . '" is not installed: cannot detect its version'
        );
    }
}
